//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisiranjeVozila
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupovina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupovina()
        {
            this.Dijelovi = new HashSet<Dijelovi>();
        }
    
        public int ID_kupovine { get; set; }
        public string Djelatnik { get; set; }
        public double Ukupna_cijena { get; set; }
        public System.DateTime Datum_kupovine { get; set; }
        public string Status_kupovina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dijelovi> Dijelovi { get; set; }
    }
}
