//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServisiranjeVozila
{
    using System;
    using System.Collections.Generic;
    
    public partial class Napredak
    {
        public int ID_napretka { get; set; }
        public string Opis { get; set; }
        public Nullable<int> ID_narudzbe { get; set; }
    
        public virtual Narudzba Narudzba { get; set; }
    }
}
