//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kupovina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kupovina()
        {
            this.Dio_u_kupovini = new HashSet<Dio_u_kupovini>();
        }
    
        public int ID_kupovine { get; set; }
        public string Zaposlenik_korime { get; set; }
        public double Ukupna_cijena { get; set; }
        public System.DateTime Datum_kupovine { get; set; }
        public string Status_kupovine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dio_u_kupovini> Dio_u_kupovini { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
