//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzba()
        {
            this.Sadrzi_dio = new HashSet<Sadrzi_dio>();
            this.Napredak = new HashSet<Napredak>();
        }
    
        public int ID_narudzbe { get; set; }
        public string Korisnicko_ime { get; set; }
        public string Napomene { get; set; }
        public System.DateTime Datum_narudzbe { get; set; }
        public Nullable<byte> Potvrđeno { get; set; }
        public Nullable<byte> Otkazano { get; set; }
        public Nullable<byte> Zavrsena { get; set; }
        public string Zaposlenik { get; set; }
        public Nullable<double> Ukupna_cijena { get; set; }
        public string Vozilo { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Korisnik Korisnik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sadrzi_dio> Sadrzi_dio { get; set; }
        public virtual Vozilo Vozilo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Napredak> Napredak { get; set; }
    }
}
