//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int ID_racuna { get; set; }
        public int ID_narudzbe { get; set; }
        public string Zaposlenik { get; set; }
        public byte[] Datum_vrijeme { get; set; }
        public double Cijena { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Narudzba Narudzba { get; set; }
    }
}
